spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false


  profiles:
    active: local
  redis:
    host: localhost
    port: 6379

#
#
#    profiles:
#      active: alpha
#    redis:
#      host: redis가 설치된 서버 호스트
#      port: redis가 설치된 서버 포트



